# Generated by Django 4.2 on 2023-05-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=122)),
                ('productDescription', models.TextField()),
                ('pubDate', models.DateField()),
            ],
        ),
    ]
