# Generated by Django 4.2.7 on 2024-01-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('ZipCode', models.CharField(max_length=52)),
                ('MobileNumber', models.IntegerField(default='')),
                ('totalPrice', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=122)),
                ('productPrice', models.IntegerField(default=0)),
                ('productDescription', models.TextField()),
                ('productImage', models.ImageField(default='', upload_to='shoppingcart/productImages')),
                ('productPublishDate', models.DateField()),
                ('productCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shoppingcart.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('orderDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('orderProductQuantity', models.IntegerField(default=0)),
                ('productPrice', models.IntegerField(default=0)),
                ('orderId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderDetailId', to='shoppingcart.order')),
                ('productId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productOrderId', to='shoppingcart.product')),
            ],
        ),
    ]
