# Generated by Django 4.2.1 on 2023-05-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pubDate',
            new_name='productPublishDate',
        ),
        migrations.AddField(
            model_name='product',
            name='productCategory',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='', upload_to='shoppingcart/productImages'),
        ),
        migrations.AddField(
            model_name='product',
            name='productPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
