# Generated by Django 4.2.7 on 2024-01-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Subject',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
