# Generated by Django 4.2.7 on 2024-05-16 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppingcart', '0003_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ZipCode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customerName',
        ),
        migrations.AddField(
            model_name='order',
            name='customerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
    ]
