# Generated by Django 4.2.1 on 2023-05-19 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppingcart', '0004_alter_product_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderAddress', models.CharField(max_length=500)),
                ('orderCountry', models.CharField(max_length=52)),
                ('orderState', models.CharField(max_length=52)),
                ('orderZipCode', models.CharField(max_length=52)),
                ('orderMobileNumber', models.IntegerField(default='')),
                ('customerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('orderDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('orderId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderDetailId', to='shoppingcart.order')),
                ('productId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productOrderId', to='shoppingcart.product')),
            ],
        ),
    ]
