# Generated by Django 4.2.7 on 2024-05-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_remove_order_zipcode_remove_order_customername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerId',
            field=models.CharField(max_length=500),
        ),
    ]
