# Generated by Django 4.2.1 on 2023-05-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0006_order_orderprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='orderProductQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
